### ISSUE TITLE
[TEST] 2024.06.25

### ISSUE THREAD

**Issue by Bini0104** [S-O-O-P/S-O-O-P-React-Admin#13]
##상세 내용
머지 후 테스트(미구현 페이지는 제외했습니다)

- 허니팟 페이지네이션 버튼 색생
- 페이지 타이틀 폰트
![image](https://github.com/S-O-O-P/S-O-O-P-React-Admin/assets/157683303/5a3ef303-dc0e-467c-b60a-be71398f4660)

- 등록 버튼 쉐도우
![image](https://github.com/S-O-O-P/S-O-O-P-React-Admin/assets/157683303/27711793-8aa2-4343-bc49-f866f12c9f4b)
![image](https://github.com/S-O-O-P/S-O-O-P-React-Admin/assets/157683303/381adf7c-f4af-40a2-b0b9-49239ca19a3d)

- 허니팟 상세페이지 취소버튼 실행 X
- 1:1 문의 답변등록 후 돌아가는 페이지 수정

**Comment by shubiduba1212** [comment]
@rlawlsdyd5932 님께서 수정하셨습니다.
