### ISSUE TITLE
[FEATURE][EVENTSINFO][REGISTER] 공연/전시 얼리버드 정보 등록 페이지

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React-Admin#6]
## 💼 어떤 기능인가요?
> 관리자 > 공연/전시 얼리버드 정보를 등록하는 페이지입니다.

## ✅ 작업 상세 내용
- [x] 레이아웃 작업
- [x] 입력 영역 유효성 검사
- [x] 등록 팝업창 작동 JS

### Figma 작업내용
![전시 정보 등록](https://github.com/S-O-O-P/S-O-O-P-React-Admin/assets/73331620/14cb65ea-23af-4936-9e21-212600c8e49b)

**Comment by rlawlsdyd5932** [comment]
확인했습니다.
