### ISSUE TITLE
[FEATURE][COMMON] FONT 적용 안되는 에러

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React-Admin#7]
##  💼 어떤 기능인가요?
> FONT 적용이 안되는 에러로, mui ui 라이브러리 자체 적용 css가 우선 적용되어서 globalStyles에서 설정한 SUIT 폰트가 제대로 적용되지 않습니다.

## ✅ 작업 상세 내용
- [x] FONT-FAMILY 속성을 mui ui 라이브러리 자체 적용 css보다 우선 적용되는 방법 모색
- [ ] 위의 방법 모색이 어려운 경우, FONT-FAMILY 속성을 클래스명 및 아이디를 사용해서 우선 순위를 올린 후, 모든 TEXT태그에 적용

## 🐝 예상 결과

> globalStyles에서 설정한 SUIT 폰트가 제대로 우선 적용되어,  mui ui 라이브러리 자체 적용 css에서 설정된 폰트가 적용되지 않는 것

**Comment by rlawlsdyd5932** [comment]
-npm install @mui/material @emotion/react @emotion/styled-
-[ ]mui 컴포넌트 템플릿은 기본적으로 roboto 폰트를 제공 하지만 저희 팀에서 쓰기로 한 폰트는 SUIT 

해결 방법
 ![image](https://github.com/S-O-O-P/S-O-O-P-React-Admin/assets/157683550/0190537a-a38f-4a8f-b8bc-309b436b288c)
Layout에다가  typography에 대한 fontFamily 새롭게 지정

**Comment by shubiduba1212** [comment]
> -npm install @mui/material @emotion/react @emotion/styled- -[ ]mui 컴포넌트 템플릿은 기본적으로 roboto 폰트를 제공 하지만 저희 팀에서 쓰기로 한 폰트는 SUIT
> 
> 해결 방법 ![image](https://private-user-images.githubusercontent.com/157683550/342198929-0190537a-a38f-4a8f-b8bc-309b436b288c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTQ1NzYsIm5iZiI6MTcxOTIxNDI3NiwicGF0aCI6Ii8xNTc2ODM1NTAvMzQyMTk4OTI5LTAxOTA1MzdhLWEzOGYtNGE4Zi1iOGJjLTMwOWI0MzZiMjg4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNzMxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjEzYmUyY2VjYjI1YTdkMzUzOTM2MjU3ZjQwOTUxZjQ2YjJlMzEzZjc0ZWQ5OGI1ZmFiNGE1NGQ5ZGNmNGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jt5BedDaPc75mlH4B4xJhedL0LxbXLRCMY9jJt5OkAE) Layout에다가 typography에 대한 fontFamily 새롭게 지정

확인했습니다😊 - 역시, 방법을 찾으셨군요! - 수정 감사합니다!
