### ISSUE TITLE
[FEATURE][EVENTSINFO][DETAIL] 공연/전시 얼리버드 정보 상세 페이지

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React-Admin#8]
## 💼 어떤 기능인가요?
등록한 공연/전시 얼리버드 정보 상세 페이지입니다.

## ✅ 작업 상세 내용
- [x] 레이아웃
- [x] 수정버튼 클릭시, 수정 페이지로 이동
- [x] 삭제버튼 클릭시, 삭제 팝업창 작동 JS

**Comment by rlawlsdyd5932** [comment]
확인했습니다.
