### ISSUE TITLE
[FEATURE][COMMON] 검색바 이중 border 표시

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-React-Admin#9]
##  💼 어떤 기능인가요?
>  관리자 > 메뉴 메인 페이지 상단 부분에서 검색바 이중 border 표시되는 에러

## ✅ 작업 상세 내용
- [x] 검색바 이중 border 제거

## 🐝 예상 결과

> 페이지 상단 부분에서 검색바 border가 메인 컬러로 하나만 표시되어야 합니다.

**Comment by Bini0104** [comment]
확인했습니다!

**Comment by rlawlsdyd5932** [comment]
확인했습니다.

**Comment by shubiduba1212** [comment]
@rlawlsdyd5932  님이  수정하셨습니다. 감사합니다!
